### ISSUE TITLE
Issues with SendHttpRequest function in SlackApi.h

### ISSUE THREAD

**Issue by TexasRanger-ops** [FSecureLABS/C3#15]
As it works with the Slack channel, this is for reference if the same function is to be used in the development of other channels. You mention in the code comments that the default request method is GET, but it appears to actually send a POST request with a 0 body due to weird handling of the NULL value passed into the data parameter. This works fine with Slack's API as they don't seem to care about the difference, but does raise issues when other API's (Microsoft for example) require it to be a GET request.

Thanks for the awesome project!

**Comment by grzryc** [comment]
👍 Good catch

**Comment by TexasRanger-ops** [comment]
Thank you! Its been really impressive code to work with. I have to give you
guys credit for following standards so well and building a modular platform
that allows for easy 3rd party additions, great work!
