### ISSUE TITLE
Update dependency 'vis'

### ISSUE THREAD

**Issue by mojoaxel** [FSecureLABS/C3#16]
You are still using a very outdated version 4.21 of vis.
This version is not supported anymore!

Please update to the new libraries:
https://github.com/visjs

Feel free to contact us if you need any support during the transition :-)

**Comment by grzryc** [comment]
Many thanks for bringing that up. We've updated them now in https://github.com/FSecureLABS/C3/commit/1be86e7ddb9660f3b1934f20bebbf4ffddafcf08
