### ISSUE TITLE
O365 Outlook/OneDrive missing header and Base64 error for O365 Task

### ISSUE THREAD

**Issue by merrillmatt011** [FSecureLABS/C3#24]
Hello,

I don't know if it was something related to how I setup the Azure applications, but I had to add the header (client_secret) to the RefreshAccessToken function and update the GetCapabilities to ask for the client_secret. Also, I had to update the OutlookTask OnReceiveFromChannel function due to an error Base64 decoding the task contents.

**Comment by pawelkurowski** [comment]
If your app is a public client, then the `client_secret` or `client_assertion` cannot be included. If the app is a confidential client, then it must be included. I've decided on this flow, to minimize number of steps needed to create channel, as well as number of parameters needed by C3. Could you elaborate on base64 decoding error? Ideally, screenshot of your problem and fix proposal.

P.S. Since publication of both O365 channel, Microsoft have created rules that can detect C2 over those services. There is approximately 3h of use, before MS disables your account. Some research is needed in order to workaround those security measures.

**Comment by merrillmatt011** [comment]
Okay, makes sense on the client_secret portion, and the following error was what I was getting:
`Warning> [0001] Caught a std::exception when running OnReceive(): parse error: character [60 '<'] out of bounds`
With the following as the data:
```
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="Generator" content="Microsoft Exchange Server">
<!-- converted from text -->
<style><!-- .EmailQuote { margin-left: 1pt; padding-left: 4pt; border-left: #800000 2px solid; } --></style></head>
<body>
<font size="2"><span style="font-size:11pt;"><div class="PlainText">[Base64 string removed]</div></span></font>
</body>
</html>
```
Changing the OnReceive function to the following corrected the issue:
```
std::vector<FSecure::ByteVector> FSecure::C3::Interfaces::Channels::Outlook365RestTask::OnReceiveFromChannel()
{
	RateLimitDelay(m_MinUpdateDelay, m_MaxUpdateDelay);
	auto packets = std::vector<ByteVector>{};
	try
	{
		auto fileList = ListData(OBF("?top=1000&filter=startswith(Subject,'") + m_InboundDirectionName + OBF("')&orderby=CreatedDateTime"));
		for (auto& element : fileList.at(OBF("value")))
		{
			std::string htmlContent = element.at(OBF("Body")).at(OBF("Content"));
			Log({ OBF_SEC("Element.At(\"Body\").At(\"Content\") is: ") + htmlContent, LogMessage::Severity::DebugInformation });
			std::string divStartStr = "<div class=\"PlainText\">";
			std::string divEndStr = "</div>";
			int divStart = htmlContent.find(divStartStr);
			if (divStart != -1) {
				int divEnd = htmlContent.find(divEndStr, divStart);
				if (divEnd != -1) {
					int startPos = divStart + divStartStr.length();
					int count = divEnd - startPos;
					std::string b64content = htmlContent.substr(startPos, count);
					packets.push_back(base64::decode<ByteVector, std::string>(b64content));
				}
			}
		}
		for (auto& element : fileList.at(OBF("value")))
			RemoveItem(element.at(OBF("Id")));
	}
	catch (std::exception& exception)
	{
		Log({ OBF_SEC("Caught a std::exception when running OnReceive(): ") + exception.what(), LogMessage::Severity::Warning });
	}
	return packets;
}
```
